<?php

return [
    "first_name.required" => "The first_name input field is empty",
    "first_name.string" => "The first_name input is not string",
    "last_name.required" => "The last_name input field is empty",
    "last_name.string" => "The last_name input is not string",
    "email.required" => "The email input field is empty",
    "email.string" => "The email input is not string",
    "email.email" => "The email input is not email",
    "email.unique" => "The email input is exists",
    "email.exists" => "The email input is not exists",
    "email.send" => "The recovery code has been sent to the email successfully",
    "email.active.err" =>"The email is not Active",
    "email.active" => "The email is Active" ,
    "password.required" => "The password input field is empty",
    "password.string" => "The password input is not string",
    "password.min" => "The password input is min 8 chars",
    "password.err" => "The password input is error",
    "password_c.required" => "The password_c input field is empty",
    "password_c.string" => "The password_c input is not string",
    "password_c.same" => "The password_c input is not equal password",
    "newpassword.required" => "The new password input is required",
    "newpassword.string" => "The new password input is not string",
    "newpassword.min" => "The password input is min 8 chars",
    "phone.digits" => "The phone input is not 10 numbers",
    "phone.numeric" => "The phone input is not numeric",
    "phone.in" => "The phone input is not true || 1",
    "role.string" => "The role input is not string",
    "role.in" => "The role input The entered value does not exist",
    "setting_lang.string" => "The setting_lang input is not string",
    "setting_lang.in" => "The setting_lang input The entered value is en || ar",
    "path_photo.mimes" => "The photo input File format is not supported",
    "path_photo.in" => "The photo input is not true || 1",
    "id_category.required" => "The id_category input is required",
    "id_category.numeric" => "The id_category input is not numeric",
    "id_category.exists" => "The id_category input is not exists",
    "user.err" => "the user is not exists",
    "user.delete" => "The deletion process has been completed successfully",
    "logout" => "Successfully logged out",
    "access" => "You do not have permission for this operation.",
    "code.err" => "The code input is error",
    "send.code.suc" => "The activation code has been sent to the email successfully. Please activate the email using the code sent",
    "online.err" => "No internet connection, please try again later",
    "data.empty" => "There is no data to edit or delete",
    "data.clear" => "The content of this field has been deleted",
];
